version: "3.8"

services:

  meece-php:
    build: ./.docker/php
    container_name: meece-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "443:443"
      - "80:80"
    tty: true
    volumes:
      - .:/var/www/html
      - xdebug-data:/tmp/xdebug
    environment:
      # XDEBUG_CONFIG: remote_enable=1 start_with_request=1 log_level=0 log=/dev/stdout output_dir=/tmp/xdebug idekey=docker mode=develop,coverage,debug,profile
      PHP_IDE_CONFIG: serverName=dev.meece.com.br
      APPLICATION_ENV: development
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
       - meece-mysql
       - meece-mailhog
       - meece-redis
       - meece-rabbitmq
       - meece-elasticsearch
    networks:
      - meece-network

  meece-mysql:
    image: mysql:8.0.30
    container_name: meece-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./kalles/dumps:/tmp/dumps
    networks:
      - meece-network

  meece-mailhog: 
    image: mailhog/mailhog
    container_name: meece-mailhog
    ports: 
      - "1025:1025"
      - "8025:8025"
    networks: 
      - meece-network

  meece-redis:
    image: redis:7.0.0-alpine
    container_name: meece-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - meece-network


  meece-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: meece-rabbitmq
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=passw123
    networks:
        - meece-network

  meece-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
      container_name: meece-elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        discovery.type: "single-node"
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
        xpack.monitoring.enabled: "true"
      volumes:
        - ./.docker/elasticsearch:/usr/share/elasticsearch/data
      networks:
          - meece-network


volumes:
  xdebug-data:
    name: meece_xdebug-data
  mysql-data:

networks: 
  meece-network:
    driver: bridge