version: "3.8"

services:

  zupah-php:
    build: ./.docker/php
    container_name: zupah-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "443:443"
      - "80:80"
    tty: true
    volumes:
      - .:/var/www/html
      - xdebug-data:/tmp/xdebug
    environment:
      XDEBUG_CONFIG: mode=debug
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=dev.zupah.com.br
      APPLICATION_ENV: development
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
       - zupah-mysql
       - zupah-mailhog
       - zupah-redis
       - zupah-rabbitmq
       - zupah-elasticsearch
    networks:
      - zupah-network

  zupah-mysql:
    image: mysql:8.0.30
    container_name: zupah-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/dumps:/tmp/dumps
    networks:
      - zupah-network

  zupah-mailhog: 
    image: mailhog/mailhog
    container_name: zupah-mailhog
    ports: 
      - "1025:1025"
      - "8025:8025"
    networks: 
      - zupah-network

  zupah-redis:
    image: redis:7.0.0-alpine
    container_name: zupah-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - zupah-network


  zupah-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: zupah-rabbitmq
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=passw123
    networks:
        - zupah-network

  zupah-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
      container_name: zupah-elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        discovery.type: "single-node"
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
        xpack.monitoring.enabled: "true"
      volumes:
        - ./.docker/elasticsearch:/usr/share/elasticsearch/data
      networks:
          - zupah-network


volumes:
  xdebug-data:
    name: zupah_xdebug-data
  mysql-data:

networks: 
  zupah-network:
    driver: bridge